### ISSUE TITLE
Internal imports without extension (e.g. import {...} from './core') break Webpack 5 in strict ESM (“type”: “module”)

### ISSUE THREAD

**Issue by mdellanave** [entronad/crypto-es#54]
Hi all,
since version 3.0.0, the package is ESM (\"type\":\"module\"), but several files in dist (e.g., md5.js, other hash/ciphers) import adjacent modules without extensions: import { WordArray } from './core';. In an ESM package, this violates the “fully specified” resolution of Webpack 5 (and other bundlers/config) which requires the extension (./core.js). This results in a build error.

Crypto-es version: 3.0.0 Webpack: 5.101.3

any idea to solve it?

**Comment by entronad** [comment]
Fixed in v3.0.1, please try.

**Comment by schlundus** [comment]
this doesn't work for me 

`
import { Utf8} from 'crypto-es/dist/core.mjs';

import { Base64 } from 'crypto-es/dist/enc-base64.mjs';
`

which produces 
`
Module not found: Error: Package path ./dist/aes.mjs is not exported from package ....node_modules\crypto-es (see exports field in ....node_modules\crypto-es\package.json)
`

this works, but it's not my use case
`
import CryptoES from 'crypto-es';
`


Please correct also the documentation of the partial import
'crypto-es/lib/md5.js`  ,..... there is no lib directory... it should be `dist`

Thanks for your effort and time!

**Comment by entronad** [comment]
@schlundus 
Fixed in v3.0.2, please have a try.

**Comment by schlundus** [comment]
Thanks, but .... If i use it that way it still shows the same errors

```
import { Utf8 as CryptoJSEncUt8 } from 'crypto-es/dist/core.mjs';
import { Base64 as CryptoJSEncBase64 } from 'crypto-es/dist/enc-base64.mjs';

```
there are no Visual Studio Code errors, but webpack complains  

```
Module not found: Error: Package path ./dist/core.mjs is not exported from package ...node_modules\crypto-es (see exports field in ...node_modules\crypto-es\package.json) 
Module not found: Error: Package path ./dist/enc-base64.mjs is not exported from package ...node_modules\crypto-es (see exports field in ...node_modules\crypto-es\package.json)
```

If i use it that way
`import { Utf8 as Test } from 'crypto-es/dist/core';`

then VS Code complains about missing module or type declarations

**Comment by lisonge** [comment]
why you revert  `fix exports` https://github.com/entronad/crypto-es/commit/62c9da4d0f109a5f31c245cc70f22a09351039d7 in `v3.0.2` https://github.com/entronad/crypto-es/commit/9be4b21a22a9101ee273dfe4d19be77043f82669 ?

**Comment by entronad** [comment]
@lisonge 
@schlundus 
Thank you very much for discovering this issue. I did indeed mistakenly revert this change in the version updating commit.

I'm not sure what caused it; I might have accidentally pressed the undo shortcut. This undo action happened to be in the package.json file that was supposed to be modified, which is why I didn't notice it when I was reviewing the commit changes.

I have fixed it in v3.0.3. Please have a try.

**Comment by schlundus** [comment]
I've tried it, it doesn't change anything for me... still the same problem

**Comment by lisonge** [comment]
<img width="1106" height="692" alt="Image" src="https://github.com/user-attachments/assets/50e690fe-1493-4283-8d2a-a410b2a1366c" />

where is your fix commit ?

there is not effective changes `v3.0.3` https://github.com/entronad/crypto-es/commit/e3b1d4d7aa68efea8afa643003ee8d77c0111693

**Comment by lisonge** [comment]
you can check published files in <https://app.unpkg.com/crypto-es@latest/files/package.json>

**Comment by schlundus** [comment]
Yes but look, it looks like there are no relevant changes

<img width="1637" height="1174" alt="Image" src="https://github.com/user-attachments/assets/ba5aae41-e95f-483b-ab86-fbf32e58d768" />

**Comment by entronad** [comment]
@lisonge 
@schlundus 
The case is finally solved! It was tsdown that always modified the "exports" in package.json to a specific format whenever I executed npm publish. Because my check was performed before the publish step, I never discovered it.
I have now changed the tsdown settings to prevent it from altering the "exports" in package.json.
Please try v3.0.4. I have already confirmed on the npm website that the "exports" in the package.json for this upload is correct.

**Comment by schlundus** [comment]
Hello again...

this one still doesn't work (brings some webpack errors) ...
```
import { Utf8 as CryptoJSEncUt8 } from 'crypto-es/dist/core.mjs';
import { Base64 as CryptoJSEncBase64 } from 'crypto-es/dist/enc-base64.mjs';
```

but that one works

`import { AES, Utf8 as CryptoJSEncUt8 } from 'crypto-es';`
and also has the desired minimal "impact"

<img width="900" height="714" alt="Image" src="https://github.com/user-attachments/assets/b1b5640a-29af-448f-b0e1-f0aac00369ca" />

compared to that one
```
import CryptoES from 'crypto-es';
import CryptoES, { AES } from 'crypto-es';
```
which has nearly full "impact"..

<img width="1379" height="724" alt="Image" src="https://github.com/user-attachments/assets/7eacf8da-3cdb-435e-9cbb-ad363f08409f" />

So, for me its fixed now... 
Thanks again for your time and effort

**Comment by mdellanave** [comment]
thank you all, fixed also for me.

**Comment by entronad** [comment]
@schlundus 
@mdellanave 
@lisonge 

I haven't dealt with packaging for a TypeScript library in a long time, so it was a bit of a hassle. After some recent research, I've pretty much figured it out.

Now, I'd like to get your opinion on whether it's reasonable for me to define the import methods for this library in the following way:

- `import { Utf8 } from 'crypto-es/dist/core.mjs';` is not a good approach because it explicitly specifies the `dist` directory. Only `import { Utf8 } from 'crypto-es';` should be allowed. My index file already implements this functionality, so I just need to stop exposing `./dist/*` in `package.json` and only document the correct usage: `import { Utf8 } from 'crypto-es';`.

- `import CryptoES from 'crypto-es';` is a very legacy way of importing, dating back to the original version of CryptoJS from decades ago. This method always includes the entire library in the project (which was the only way to import libraries back then), and it's clear that no single project needs all the algorithms it contains. Since I've decided to shed this historical baggage, I should remove the `CryptoES` default export and completely prohibit the use of `import CryptoES from 'crypto-es';`.

Of course, after these changes, the documentation will need to be completely rewritten to feature only modern, tree-shakable import methods.

**Comment by lisonge** [comment]
>  tree-shakable

Actually, there is still some code in your library that is not tree-shakable, such as

<https://github.com/entronad/crypto-es/blob/b9e1f3ee8b0fe158fa4dd3c98ac0d3080bb5cf4f/src/md5.ts#L9-L16>

it should changed to

```ts
const T = /* @__PURE__ */ (() => {
  const a: number[] = [];
  for (let i = 0; i < 64; i += 1) {
    a[i] = (Math.abs(Math.sin(i + 1)) * 0x100000000) | 0;
  }
  return a;
})();
```

[example-1](https://esbuild.egoist.dev/#W1siaW5kZXgudHMiLHsiY29udGVudCI6Ii8vIENvbnN0YW50cyB0YWJsZVxuY29uc3QgVDogbnVtYmVyW10gPSBbXTtcblxuLy8gQ29tcHV0ZSBjb25zdGFudHNcbmZvciAobGV0IGkgPSAwOyBpIDwgNjQ7IGkgKz0gMSkge1xuICBUW2ldID0gKE1hdGguYWJzKE1hdGguc2luKGkgKyAxKSkgKiAweDEwMDAwMDAwMCkgfCAwO1xufSJ9XSxbImVzYnVpbGQuY29uZmlnLmpzb24iLHsiY29udGVudCI6IntcbiAgXCJmb3JtYXRcIjogXCJlc21cIixcbiAgXCJjZG5VcmxcIjogXCJodHRwczovL2VzbS5zaFwiXG59In1dXQ==)

[example-2](https://esbuild.egoist.dev/#W1siaW5kZXgudHMiLHsiY29udGVudCI6ImNvbnN0IFQgPSAvKiBAX19QVVJFX18gKi8gKCgpID0+IHtcbiAgY29uc3QgYTogbnVtYmVyW10gPSBbXTtcbiAgZm9yIChsZXQgaSA9IDA7IGkgPCA2NDsgaSArPSAxKSB7XG4gICAgYVtpXSA9IChNYXRoLmFicyhNYXRoLnNpbihpICsgMSkpICogMHgxMDAwMDAwMDApIHwgMDtcbiAgfVxuICByZXR1cm4gYTtcbn0pKCk7In1dLFsiZXNidWlsZC5jb25maWcuanNvbiIseyJjb250ZW50Ijoie1xuICBcImZvcm1hdFwiOiBcImVzbVwiLFxuICBcImNkblVybFwiOiBcImh0dHBzOi8vZXNtLnNoXCJcbn0ifV1d)

**Comment by mdellanave** [comment]
> [@schlundus](https://github.com/schlundus) [@mdellanave](https://github.com/mdellanave) [@lisonge](https://github.com/lisonge)
> 
> I haven't dealt with packaging for a TypeScript library in a long time, so it was a bit of a hassle. After some recent research, I've pretty much figured it out.
> 
> Now, I'd like to get your opinion on whether it's reasonable for me to define the import methods for this library in the following way:
> 
> * `import { Utf8 } from 'crypto-es/dist/core.mjs';` is not a good approach because it explicitly specifies the `dist` directory. Only `import { Utf8 } from 'crypto-es';` should be allowed. My index file already implements this functionality, so I just need to stop exposing `./dist/*` in `package.json` and only document the correct usage: `import { Utf8 } from 'crypto-es';`.
> * `import CryptoES from 'crypto-es';` is a very legacy way of importing, dating back to the original version of CryptoJS from decades ago. This method always includes the entire library in the project (which was the only way to import libraries back then), and it's clear that no single project needs all the algorithms it contains. Since I've decided to shed this historical baggage, I should remove the `CryptoES` default export and completely prohibit the use of `import CryptoES from 'crypto-es';`.
> 
> Of course, after these changes, the documentation will need to be completely rewritten to feature only modern, tree-shakable import methods.

I'm importing in this way 

`import { MD5 } from 'crypto-es/dist/md5';`

but I can rearrange the code in future updates if necessary, no prob

**Comment by entronad** [comment]
@schlundus 
@mdellanave 
@lisonge 

I have implemented the above plan in v3.1.0:

- Optimize tree-shakability
- Only allow partially importing from index
- A new README.

**Comment by schlundus** [comment]
Very good, please see my [comment](https://github.com/entronad/crypto-es/issues/52#issuecomment-3264816790)
